# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OutlierWeb - For Outliers & Independent Thinkers
email: richardsj896@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  OutlierWeb is Jamaica's leading web development company.
  We Provide design, e-commerce and custom internet application development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://outlierweb.com" # the base hostname & protocol for your site
twitter_username: obeeyrobbie
github_username:  robert903

# Build settings
markdown: kramdown


gems:
  - jekyll-sitemap
